### PR TITLE
[ENH] Update command and docstring

### LINKED ISSUE #716: Update Docker/Apptainer commands in "How to get data" modal
In the copy-pastable command for dataget, query results TSV filenames now have a datetime placeholder, so the default command will not work as-is.

We should:

- [x] Update the template command to have a (nonsensical) template 
- [x] Update the instructions to explain how to adjust the template

### PR DESCRIPTION
**Pull request by surchs**
To reflect the new timestamp

- Closes #716 

Changes proposed in this pull request:

-
-

## Checklist
_This section is for the PR reviewer_

- [x] PR has an interpretable title with a prefix (`[ENH]`, `[FIX]`, `[REF]`, `[TST]`, `[CI]`, `[MNT]`, `[INF]`, `[MODEL]`, `[DOC]`) _(see our [Contributing Guidelines](https://neurobagel.org/contributing/CONTRIBUTING#pull-request-guidelines) for more info)_
- [ ] PR has a label for the release changelog or `skip-release` (to be applied by maintainers only)
- [x] PR links to GitHub issue with mention `Closes #XXXX`
- [x] Tests pass
- [x] Checks pass
- [ ] If the PR changes the participant-level and/or the dataset-level result file, the [`query-tool-results` files](https://github.com/neurobagel/neurobagel_examples/tree/main/query-tool-results) in the  [neurobagel_examples repo](https://github.com/neurobagel/neurobagel_examples/) have been regenerated

For new features:
- [ ] Tests have been added

For bug fixes:
- [ ] There is at least one test that would fail under the original bug conditions.

## Summary by Sourcery

Update the data download dialog to reference the timestamped query results file and clarify how to use it in the provided container commands.

Enhancements:
- Adjust Docker and Apptainer example commands to use a timestamped neurobagel query results filename placeholder.
- Improve the step-by-step instructions in the Get Data dialog to explain replacing the placeholder filename with the actual downloaded TSV before running the command.

### CODE REVIEW

File: src/components/GetDataDialog.tsx [hunk 1]
```diff
@@ -46,7 +46,13 @@ function GetDataDialog({ open, onClose }: { open: boolean; onClose: () => void }
               results&rdquo; dropdown
             </li>
             <li>Change directory to the location of the downloaded TSV</li>
-            <li>Copy and run the command below</li>
+            <li>Take not of the filename you downloaded. It will include a timestamp at the end</li>
```
Comment (alyssadai) [inline src/components/GetDataDialog.tsx]:
```suggestion
            <li>Take note of the filename you downloaded. It will include a timestamp at the end</li>
```

File: src/components/GetDataDialog.tsx [hunk 2]
```diff
@@ -46,7 +46,13 @@ function GetDataDialog({ open, onClose }: { open: boolean; onClose: () => void }
...
+            <li>
+              Copy the command below into your terminal and replace the
```
Comment (alyssadai) [inline src/components/GetDataDialog.tsx]: 🍒
```suggestion
              Copy the below command into your terminal and replace the
```

File: src/components/GetDataDialog.tsx [hunk 3]
```diff
@@ -46,7 +46,13 @@ function GetDataDialog({ open, onClose }: { open: boolean; onClose: () => void }
...
+              &rdquo;neurobagel-query-results_00000000000000.tsv&rdquo; placeholder with your actual
+              file name. Make sure to keep the &rdquo;/data/&rdquo; part!
```
Comment (alyssadai) [inline src/components/GetDataDialog.tsx]: I find the `Make sure to keep the "/data/" part` confusing, because I'm not sure which `"/data/"` you're referring to (since it appears in 3 different places in the command).

Since the only thing that will change is the timestamp placeholder, what if we just said instead:
```suggestion
              &rdquo;YYYYMMDDHHMMSS&rdquo; placeholder with the actual time stamp 
              from your downloaded filename
```

that way it's clearer they only need to change that one part of the path (IMO)

File: src/components/GetDataDialog.tsx [hunk 4]
```diff
@@ -16,9 +16,9 @@ import CodeBlock from './CodeBlock';
 function GetDataDialog({ open, onClose }: { open: boolean; onClose: () => void }) {
   const RUN_COMMANDS: { [key: string]: string } = {
     docker:
-      'docker run -t -u $(id -u):$(id -g) -v $(pwd):/data neurobagel/dataget:latest /data/neurobagel-query-results.tsv /data/output',
+      'docker run -t -u $(id -u):$(id -g) -v $(pwd):/data neurobagel/dataget:latest /data/neurobagel-query-results_00000000000000.tsv /data/output',
```
Comment (alyssadai) [inline src/components/GetDataDialog.tsx]: 🍒 
why not:
```suggestion
      'docker run -t -u $(id -u):$(id -g) -v $(pwd):/data neurobagel/dataget:latest /data/neurobagel-query-results_YYYYMMDDHHMMSS.tsv /data/output',
```

? to me that conveys more obviously that this is a placeholder for a timestamp

**Review by alyssadai — APPROVED** [review]
Thanks @surchs for addressing this! I left two suggestions about the placeholder and what to include as the thing to "replace" in the template command. Have a look, then 🧑‍🍳
