### PR TITLE
[ENH] Add error alert component to display errors

### LINKED ISSUE #505: Display node errors from f-API
### Is there an existing issue for this?

- [x] I have searched the existing issues

### New feature

Currently, if all selected nodes in a query fail to respond, the user is faced with the following message:

Image

along with an error alert that says `All nodes failed to respond!`

When this happens, in order to find out what the cause of the failure was, we need to either send a direct request to the f-API or n-API to see the actual API response, or ask the user to do so on their end. This is a bit tedious especially for non-public nodes and creates extra work during debugging, and could be avoided if we could leverage the user-friendly response structure from the f-API (which organizes errors from each node, etc.) in the query tool UI itself. 

One option, since the query tool already creates an alert for any errors, could be to print the `"errors"` content for f-API response in the error alert itself (when it is non-empty):

```json
{
  "errors": [
    {
      "node_name": "Alliance FRQS node",
      "error": "Internal Server Error: {\"detail\":\": Query evaluation error: Insufficient free Heap Memory 247Mb for group by and distinct, threshold:250Mb, reached 2Mb (HTTP status 500)\\n\"}"
    }
  ],
  "responses": [],
  "nodes_response_status": "fail"
}
```

- Related: https://github.com/neurobagel/query-tool/issues/338

### Unclear documentation

_No response_

TODO:
- [x] read out `detail` field from error response
- [x] Display the error description prominently on the UI (e.g. in a non-closing toast)
- [x] Write a test for the error display functionality

Decision: make component on top of results with errors in it

### LINKED ISSUE #598: Remove `defaultProps` for functional components
`defaultProps` is deprecated in React.

See https://react.dev/blog/2024/04/25/react-19-upgrade-guide#removed-proptypes-and-defaultprops

We still have it in some components because of our linting rules (they apparently aren't updated). For now what we can do is:

- [ ] Disable the `react/require-default-props` eslint rule
- [ ] switch to default parameters and remove `defaultProps`

Eventually we could explore adopting a different eslint ruleset like https://github.com/Rel1cx/eslint-react

### PR DESCRIPTION
**Pull request by surchs**
- Closes #505
- Closes #598 

Changes proposed in this pull request:

- Factor out the code block from the getData component into its own component
- add new ErrorAlert component
- Add text for when certain kinds of errors are shown.

## Checklist
_This section is for the PR reviewer_

- [x] PR has an interpretable title with a prefix (`[ENH]`, `[FIX]`, `[REF]`, `[TST]`, `[CI]`, `[MNT]`, `[INF]`, `[MODEL]`, `[DOC]`) _(see our [Contributing Guidelines](https://neurobagel.org/contributing/CONTRIBUTING#pull-request-guidelines) for more info)_
- [x] PR has a label for the release changelog or `skip-release` (to be applied by maintainers only)
- [x] PR links to GitHub issue with mention `Closes #XXXX`
- [x] Tests pass
- [x] Checks pass
- [ ] If the PR changes the participant-level and/or the dataset-level result file, the [`query-tool-results` files](https://github.com/neurobagel/neurobagel_examples/tree/main/query-tool-results) in the  [neurobagel_examples repo](https://github.com/neurobagel/neurobagel_examples/) have been regenerated

For new features:
- [ ] Tests have been added

For bug fixes:
- [ ] There is at least one test that would fail under the original bug conditions.

## Summary by Sourcery

Add an ErrorAlert component and integrate it into the main UI for handling network errors, partial successes, and failures; refactor API response types for consistency; replace previous snackbar notifications with the new alert; and update related tests and lint/format scripts.

New Features:
- Introduce an ErrorAlert component to display API error titles, explanations, and optional error details

Enhancements:
- Replace snackbar and notification-based error handling in App.tsx with the new ErrorAlert component
- Centralize API response fields by extracting BaseAPIResponse and updating QueryResponse, RetrievedAttributeOption, and RetrievedPipelineVersions to extend it
- Implement resultStatus state and mapping logic in App.tsx to drive error alert rendering

Build:
- Update lint and format scripts in package.json to support file-scoped checks and fixes

Tests:
- Add component tests for ErrorAlert to verify rendering and scrolling behavior
- Update end-to-end Cypress tests to assert error-alert usage instead of snackbars

## Summary by Sourcery

Add a reusable ErrorAlert component and CodeBlock extraction, integrate improved error handling in the main UI, refactor API response typing for consistency, and update tests and build scripts accordingly

New Features:
- Introduce ErrorAlert component to display API error titles, explanations, and optional details with expand/collapse behavior

Enhancements:
- Replace snackbar and popover notifications with the ErrorAlert component in App.tsx for network errors, partial successes, and failures
- Extract CodeBlock component to render and copy code snippets in GetDataDialog
- Centralize API response types by adding BaseAPIResponse and extending it in QueryResponse, RetrievedAttributeOption, and RetrievedPipelineVersions

Build:
- Update lint and format scripts in package.json to support file-scoped checks and fixes

Tests:
- Add Cypress component tests for ErrorAlert to verify rendering, scrolling, and expand/collapse behavior
- Update end-to-end Cypress tests to assert use of ErrorAlert and CodeBlock instead of snackbars and popovers

### CODE REVIEW

File: src/components/CodeBlock.tsx [hunk 1]
```diff
@@ -0,0 +1,58 @@
+import React, { useState } from 'react';
+import { IconButton, Popover, Typography } from '@mui/material';
+import ContentCopyIcon from '@mui/icons-material/ContentCopy';
+
```
Comment (rmanaem) [inline src/components/CodeBlock.tsx:5]:
```suggestion
import NBTheme from '../theme';
```

File: src/components/CodeBlock.tsx [hunk 2]
```diff
@@ -0,0 +1,58 @@
...
+        sx={{
+          position: 'absolute',
+          top: 0,
+          right: 16,
+        }}
+      >
+        <ContentCopyIcon fontSize="small" />
+      </IconButton>
+      <Popover open={showPopover} anchorEl={buttonRef.current} onClose={handleClose}>
+        <Typography className="rounded px-2 py-1 text-sm text-white shadow">Copied!</Typography>
```
Comment (rmanaem) [inline src/components/CodeBlock.tsx]: Right now since the background is white the `Copied!` text doesn't appear.

```suggestion
        <Typography className="rounded px-2 py-1 text-sm text-white shadow" sx={{ backgroundColor: NBTheme.palette.primary.main }}>Copied!</Typography>
```

File: cypress/component/ErrorAlert.cy.tsx [hunk 3]
```diff
@@ -0,0 +1,70 @@
+import ErrorAlert from '../../src/components/ErrorAlert';
+import { failedQueryResponse } from '../fixtures/mocked-responses';
+
+const errorTitle = 'errorTitle';
+const explanation = 'something went wrong.';
+const errorMessage = JSON.stringify(failedQueryResponse, null, 2);
```
Comment (rmanaem) [inline cypress/component/ErrorAlert.cy.tsx]: To match the existing tests:

```suggestion
const props = {
    errorTitle : 'errorTitle',
    explanation : 'something went wrong.',
    errorMessage : JSON.stringify(failedQueryResponse, null, 2)
}
```

File: cypress/component/CodeBlock.cy.tsx [hunk 4]
```diff
@@ -0,0 +1,42 @@
+import CodeBlock from '../../src/components/CodeBlock';
+
+const codeExample = JSON.stringify(
+  { error: [{ key: 'value' }, { key: 'value' }, { key: 'value' }] },
+  null,
+  2
+);
```
Comment (rmanaem) [inline cypress/component/CodeBlock.cy.tsx]:
```suggestion
const props = {
    codeExample : JSON.stringify(
  { error: [{ key: 'value' }, { key: 'value' }, { key: 'value' }] },
  null,
  2
)}
```

File: src/App.tsx [hunk 5]
```diff
@@ -437,34 +439,35 @@ function App() {
...
-      enqueueSnackbar('Failed to retrieve results', { variant: 'error', action });
+      setResultStatus('network error');
     }
     setLoading(false);
   }
 
+  const queryHasFailed = resultStatus !== 'success';
+  const queryErrorMessage = result ? JSON.stringify(result.errors, null, 2) : '';
+  const queryErrorMapping: {
+    [key: string]: { errorTitle: string; explanation: string; errorLevel: string };
```
Comment (rmanaem) [inline src/App.tsx]:
```suggestion
    [key: string]: { errorTitle: string; explanation: string; severity: string };
```

File: src/App.tsx [hunk 6]
```diff
@@ -437,34 +439,35 @@ function App() {
...
+  } = {
+    'network error': {
+      errorTitle: 'Network Error',
+      explanation: 'Please check your internet connection and try again.',
+      errorLevel: 'error',
```
Comment (rmanaem) [inline src/App.tsx]:
```suggestion
      severity: 'error',
```

File: src/App.tsx [hunk 7]
```diff
@@ -437,34 +439,35 @@ function App() {
...
+    },
+    'partial success': {
+      errorTitle: 'Partial Success',
+      explanation: 'Some nodes failed to respond. Please try again later.',
+      errorLevel: 'warning',
```
Comment (rmanaem) [inline src/App.tsx]:
```suggestion
      severity: 'warning',
```

File: src/App.tsx [hunk 8]
```diff
@@ -437,34 +439,35 @@ function App() {
...
+    },
+    fail: {
+      errorTitle: 'Query Failed',
+      explanation: 'Please check your query and try again.',
+      errorLevel: 'error',
```
Comment (rmanaem) [inline src/App.tsx]:
```suggestion
      severity: 'error',
```

**Review by rmanaem — CHANGES_REQUESTED** [review]
Thanks for addressing this @surchs!

:cherries: One thing to address is to remove the existing failure text from `ResultContainer` since we will now get both that text and the newly implemented error alert.
Other than that I left a few suggestions, please take a look.

File: src/.vscode/settings.json [hunk 9]
```diff
@@ -0,0 +1,6 @@
+{
```
Comment (rmanaem) [inline src/.vscode/settings.json]: Was pushing this intentional?

File: src/.vscode/task.json [hunk 10]
```diff
@@ -0,0 +1,25 @@
+{
```
Comment (rmanaem) [inline src/.vscode/task.json]: Same as above, intentional?

**Review by rmanaem — CHANGES_REQUESTED** [review]
Hey @surchs,
I think forgot to remove the failed text from `ResultContainer` component.
I also comments about the `.vscode` files. Not sure if they were intentional but I think they shouldn't be added to the repo

**Comment by surchs** [comment]
Thanks @rmanaem for catching the stuff left in the ResultContainer! Should we release off this PR?

**Review by rmanaem — APPROVED** [review]
🧑‍🍳 

> Should we release off this PR?

Please do.
