### PR TITLE
[FIX] Refactored syncing of the `URLSearchParams` and selected nodes

### LINKED ISSUE #24: Refactor the synching of the `URLSearchParams` and selected nodes

### PR DESCRIPTION
**Pull request by rmanaem**
- Closes #24 

## Checklist

- [x] PR has an interpretable title with a prefix (`[ENH]`, `[FIX]`, `[REF]`, `[TST]`, `[CI]`, `[MNT]`, `[INF]`, `[MODEL]`, `[DOC]`) _(see https://neurobagel.org/contributing/pull_requests for more info)_
- [x] PR links to GitHub issue with mention `Closes #XXXX`
- [x] Tests pass
- [x] Checks pass

For new features:
- [ ] Tests have been added

For bug fixes:
- [ ] There is at least one test that would fail under the original bug conditions.

### CODE REVIEW

File: src/App.tsx [hunk 1]
```diff
@@ -41,6 +40,10 @@ function App() {
   const [imagingModality, setImagingModality] = useState<FieldInput>(null);
   const [searchParams, setSearchParams] = useSearchParams();
 
+  const node: FieldInputOption[] = nodeOptions
+    .filter((n) => searchParams.getAll('node').includes(n.NodeName))
+    .map((n) => ({ label: n.NodeName, id: n.ApiURL }));
```
Comment (surchs) [inline src/App.tsx:45]: maybe use a different name here, so we don't have `n` twice - that's confusing

Comment (surchs) [reply src/App.tsx:45]: how about `availableNode` and `selectedNode`?

File: src/App.tsx [hunk 2]
```diff
@@ -98,42 +101,29 @@ function App() {
...
-          );
-          setNode(filteredNode);
-          setSearchParams({ node: filteredNode.map((n) => n.label) });
-        } else if (Array.isArray(node) && !arraysEqual(node, matchedOptions)) {
-          setNode(matchedOptions);
+          const filteredNodeNames = matchedNodeNames.filter((nodeName) => nodeName !== 'All');
+          setSearchParams({ node: filteredNodeNames });
         }
-      }
+      }
```
Comment (surchs) [inline src/App.tsx:124]: extra whitespace seems superfluous. mind running prettier again?

**Review by surchs — APPROVED** [review]
nice! thanks @rmanaem

one suggestion and then :cook:

File: src/App.tsx (hunk 1 above)
Comment (rmanaem) [reply src/App.tsx:45]: > maybe use a different name here, so we don't have n twice - that's confusing

Shouldn't be the same since we're chaining of off the available nodes? We filter the options and then map the same filtered options.

Comment (surchs) [reply src/App.tsx]: the same type/shape, yes. But it's a different variable name. The only thing that separates them is the scope - but it makes it tricky to read / possible to get confused

**Comment by surchs** [comment]
:rocket: PR was released in [`v0.1.0`](https://github.com/neurobagel/query-tool/releases/tag/v0.1.0) :rocket:
