### PR TITLE
[ENH] Implement Notification Icon with Badge for Warnings and Its Test

### LINKED ISSUE #393: Make non-critical warnings less intrusive
### Is there an existing issue for this?

- [x] I have searched the existing issues

### New feature

I would like to have a way of removing / hiding the non-critical warnings from the UI. Right now I get a lot of warnings even if nothing is really broken - and as a regular user I cannot do anything about these warnings (other than click them away one by one):

Image

I propose we make the current behaviour a "debug" mode and make it default to "off". In the new "normal mode", I would either see only critical error messages (i.e. no results / something broken) or I see only a little counter of warnings and errors - e.g. with a badge https://mui.com/material-ui/react-badge/

Image

I can then do some UI action (e.g. click the badge) to expand these warnings and look at them. 

### Unclear documentation

_No response_

### PR DESCRIPTION
**Pull request by Tusharjamdade**
- Closes #393 

Changes proposed in this pull request:

- Implemented a notification badge for non-critical warnings
- Additionally, added a test for the notification badge

## Checklist
_This section is for the PR reviewer_

- [x] PR has an interpretable title with a prefix (`[ENH]`, `[FIX]`, `[REF]`, `[TST]`, `[CI]`, `[MNT]`, `[INF]`, `[MODEL]`, `[DOC]`) _(see our [Contributing Guidelines](https://neurobagel.org/contributing/CONTRIBUTING#pull-request-guidelines) for more info)_
- [x] PR has a label for the release changelog or `skip-release` (to be applied by maintainers only)
- [x] PR links to GitHub issue with mention `Closes #XXXX`
- [x] Tests pass
- [x] Checks pass
- [ ] If the PR changes the participant-level and/or the dataset-level result file, the [`query-tool-results` files](https://github.com/neurobagel/neurobagel_examples/tree/main/query-tool-results) in the  [neurobagel_examples repo](https://github.com/neurobagel/neurobagel_examples/) have been regenerated

For new features:
- [x] Tests have been added

For bug fixes:
- [ ] There is at least one test that would fail under the original bug conditions.

## Summary by Sourcery

Add a notification icon with a badge to display non-critical warnings to the user.

New Features:
- Display non-critical warnings as notifications in a popover.

Tests:
- Add tests for the notification icon and badge.

### CODE REVIEW

File: src/components/Navbar.tsx [hunk 1]
```diff
@@ -8,30 +8,55 @@ import {
...
+}: {
+  isLoggedIn: boolean;
+  onLogin: () => void;
+  notifications: string[];
+}) {
   const [anchorEl, setAnchorEl] = useState<null | HTMLElement>(null);
   const openAccountMenu = Boolean(anchorEl);
 
   const { user, logout } = useAuth0();
+  const [anchorMailEl, setAnchorMailEl] = useState<null | HTMLElement>(null);
```
Comment (rmanaem) [inline src/components/Navbar.tsx]:
```suggestion
  const [anchorNotifEl, setAnchorNotifEl] = useState<null | HTMLElement>(null);
```

Since we switched out the mail icon for notification, it's good to update the relevant variables.

File: src/components/Navbar.tsx [hunk 2]
```diff
@@ -8,30 +8,55 @@ import {
...
+  const openMailMenu = Boolean(anchorMailEl);
```
Comment (rmanaem) [inline src/components/Navbar.tsx]:
```suggestion
  const openNotifMenu = Boolean(anchorNotifEl);
```

File: src/components/Navbar.tsx [hunk 3]
```diff
@@ -8,30 +8,55 @@ import {
...
     setAnchorEl(event.currentTarget);
   };
+
   const handleClose = () => {
     setAnchorEl(null);
   };
 
+  const handleMailClick = (event: React.MouseEvent<HTMLElement>) => {
+    setAnchorMailEl(event.currentTarget);
+  };
```
Comment (rmanaem) [inline src/components/Navbar.tsx]:
```suggestion
  const handleNotifClick = (event: React.MouseEvent<HTMLElement>) => {
    setAnchorNotifEl(event.currentTarget);
  };
```

File: src/components/Navbar.tsx [hunk 4]
```diff
@@ -8,30 +8,55 @@ import {
...
+
+  const handleMailClose = () => {
+    setAnchorMailEl(null);
```
Comment (rmanaem) [inline src/components/Navbar.tsx]:
```suggestion
  const handleNotifClose = () => {
    setAnchorNotifEl(null);
```

File: src/components/Navbar.tsx [hunk 5]
```diff
@@ -56,9 +81,83 @@ function Navbar({ isLoggedIn, onLogin }: { isLoggedIn: boolean; onLogin: () => v
               <Article />
             </IconButton>
           </Tooltip>
+          <Tooltip title="Notifications">
+            <IconButton onClick={handleMailClick}>
```
Comment (rmanaem) [inline src/components/Navbar.tsx]:
```suggestion
            <IconButton onClick={handleNotifClick}>
```

File: src/components/Navbar.tsx [hunk 6]
```diff
@@ -56,9 +81,83 @@ function Navbar({ isLoggedIn, onLogin }: { isLoggedIn: boolean; onLogin: () => v
...
+              <Badge badgeContent={notifications.length} color="primary">
+                <NotificationsIcon color="action" />
+              </Badge>
+            </IconButton>
+          </Tooltip>
+          <Popover
+            open={openMailMenu}
+            anchorEl={anchorMailEl}
+            onClose={handleMailClose}
```
Comment (rmanaem) [inline src/components/Navbar.tsx]:
```suggestion
            open={openNotifMenu}
            anchorEl={anchorNotifEl}
            onClose={handleNotifClose}
```

File: src/components/Navbar.tsx [hunk 7]
```diff
@@ -56,9 +81,83 @@ function Navbar({ isLoggedIn, onLogin }: { isLoggedIn: boolean; onLogin: () => v
...
+            anchorOrigin={{
+              vertical: 'bottom',
+              horizontal: 'right',
+            }}
+            transformOrigin={{
+              vertical: 'top',
+              horizontal: 'right',
+            }}
+            PaperProps={{
```
Comment (rmanaem) [inline src/components/Navbar.tsx]: I believe the `PaperProps` is deprecated see the relevant documentation section [here](https://v5.mui.com/material-ui/api/popover/#popover-prop-PaperProps)

File: src/components/Navbar.tsx [hunk 8]
```diff
@@ -56,9 +81,83 @@ function Navbar({ isLoggedIn, onLogin }: { isLoggedIn: boolean; onLogin: () => v
...
+                  <ListItem
+                    key={notification}
+                    alignItems="flex-start"
+                    className="mb-2 rounded-md border-l-4 border-[#FF9800] bg-[#FFF3E0] transition-colors duration-200 hover:bg-gray-200"
+                  >
+                    <ListItemText
+                      primary={
+                        <Typography variant="subtitle2" className="font-bold text-[#E65100]">
+                          {/* Add the appropriate title for the notification if any */}
+                        </Typography>
```
Comment (rmanaem) [inline src/components/Navbar.tsx]: I think we can use the type of notification e.g., warning, error, info for the primary content.

File: src/components/Navbar.tsx [hunk 9]
```diff
@@ -56,9 +81,83 @@ function Navbar({ isLoggedIn, onLogin }: { isLoggedIn: boolean; onLogin: () => v
...
+                          {notification}
+                        </Typography>
+                      }
+                    />
+                    <ListItemSecondaryAction>
+                      <IconButton
+                        edge="end"
+                        aria-label="delete"
+                        className="text-[#FF5722] hover:bg-[#FF572220]"
+                      />
```
Comment (rmanaem) [inline src/components/Navbar.tsx]: You may have forgotten to add the delete icon and implement the logic for deleting a list item.

File: src/components/Navbar.tsx [hunk 10]
```diff
@@ -56,9 +81,83 @@ function Navbar({ isLoggedIn, onLogin }: { isLoggedIn: boolean; onLogin: () => v
...
+              },
+            }}
+          >
+            <List className="w-full max-w-[360px] overflow-y-auto bg-white">
+              {notifications.length > 0 ? (
+                notifications.map((notification) => (
+                  <ListItem
+                    key={notification}
+                    alignItems="flex-start"
+                    className="mb-2 rounded-md border-l-4 border-[#FF9800] bg-[#FFF3E0] transition-colors duration-200 hover:bg-gray-200"
```
Comment (rmanaem) [inline src/components/Navbar.tsx]: The issue with this implementation is it doesn't take into account the type of notification and colors them all the same see other comments for more context

File: cypress/component/Navbar.cy.tsx [hunk 11]
```diff
@@ -24,5 +31,7 @@ describe('Navbar', () => {
     cy.get("[data-cy='navbar'] a")
       .eq(1)
       .should('have.attr', 'href', 'https://github.com/neurobagel/query-tool/');
+    // Test for Notification Icon and Badge
+    cy.get("[data-cy='navbar'] button").eq(1).find('svg').should('be.visible'); // Check if the notification icon exists
```
Comment (rmanaem) [inline cypress/component/Navbar.cy.tsx]: It's good to expand this test to include some assertions about the contents of the popover

**Review by rmanaem — CHANGES_REQUESTED** [review]
Hi @Tusharjamdade,

Congratulations on your first contribution to Neurobagel! 🎉 The changes look great overall. However, there are a few areas that need adjustments:

- Currently, the implementation doesn't support deleting notifications, either individually or all at once.
- The way warnings are passed to the Navbar component is too specific, limiting reusability.
- Some of the e2e and component tests are failing due to these changes.

To address these, we can:

- Implement delete functionality for each notification and a "clear all notifications" feature for the popover.
- Refactor the logic for passing notifications to the Navbar component to make it more generic. This will allow us to pass different types of notifications (info, errors) to the Navbar.
  -  For that the type of notification so that the appropriate title and color can be set in the ListItemText.
  - Once the logic is updated, we can also display info notifications in the popover.
- Update the tests to reflect these changes.

I understand this might be overwhelming for your first PR and contribution. Please don't hesitate to reach out with any questions, or let us know if you would prefer one of the maintainers to take over this PR.

**Comment by Tusharjamdade** [comment]
> Hi @Tusharjamdade,
> 
> Congratulations on your first contribution to Neurobagel! 🎉 The changes look great overall. However, there are a few areas that need adjustments:
> 
> * Currently, the implementation doesn't support deleting notifications, either individually or all at once.
> * The way warnings are passed to the Navbar component is too specific, limiting reusability.
> * Some of the e2e and component tests are failing due to these changes.
> 
> To address these, we can:
> 
> * Implement delete functionality for each notification and a "clear all notifications" feature for the popover.
> * Refactor the logic for passing notifications to the Navbar component to make it more generic. This will allow us to pass different types of notifications (info, errors) to the Navbar.
>   
>   * For that the type of notification so that the appropriate title and color can be set in the ListItemText.
>   * Once the logic is updated, we can also display info notifications in the popover.
> * Update the tests to reflect these changes.
> 
> I understand this might be overwhelming for your first PR and contribution. Please don't hesitate to reach out with any questions, or let us know if you would prefer one of the maintainers to take over this PR.

Thank you for the review, @rmanaem.

I appreciate the detailed feedback and suggestions.
I will work on the details shared and will reach out if I need any help!!

**Comment by Tusharjamdade** [comment]
> Hi @Tusharjamdade,
> 
> Congratulations on your first contribution to Neurobagel! 🎉 The changes look great overall. However, there are a few areas that need adjustments:
> 
> * Currently, the implementation doesn't support deleting notifications, either individually or all at once.
> * The way warnings are passed to the Navbar component is too specific, limiting reusability.
> * Some of the e2e and component tests are failing due to these changes.
> 
> To address these, we can:
> 
> * Implement delete functionality for each notification and a "clear all notifications" feature for the popover.
> * Refactor the logic for passing notifications to the Navbar component to make it more generic. This will allow us to pass different types of notifications (info, errors) to the Navbar.
>   
>   * For that the type of notification so that the appropriate title and color can be set in the ListItemText.
>   * Once the logic is updated, we can also display info notifications in the popover.
> * Update the tests to reflect these changes.
> 
> I understand this might be overwhelming for your first PR and contribution. Please don't hesitate to reach out with any questions, or let us know if you would prefer one of the maintainers to take over this PR.

Hi @rmanaem 
```tsx
export type Notification = {
  id: number;
  type: 'info' | 'warning';
  message: string;
};

const [notifications, setNotifications] = useState<Notification[]>([]);

<Navbar
  isLoggedIn={isAuthenticated}
  onLogin={() => setOpenAuthDialog(true)}
  notifications={notifications}
  setNotifications={setNotifications}
/>

// Navbar component
function Navbar({
  isLoggedIn,
  onLogin,
  notifications,
  setNotifications
}: {
  isLoggedIn: boolean;
  onLogin: () => void;
  notifications: Notification[];
  setNotifications: React.Dispatch<React.SetStateAction<Notification[]>>;
}) 
```
This is an overview of the implementation I have used. I have stored all notifications based on their types (warning, info) and messages, assigning each one a unique identifier (which will be used to delete the notification when the delete icon is clicked).

I passed the notifications and setNotifications to update the notifications (when the user clicks the delete button or the clear all button). Is this approach acceptable, or do I need to work on something else?

**Comment by rmanaem** [comment]
Hi @Tusharjamdade,
That's a good approach. Could you push your changes so I can take a look at them in context?

**Comment by Tusharjamdade** [comment]
> Hi @Tusharjamdade, That's a good approach. Could you push your changes so I can take a look at them in context?

Hi @rmanaem,

I am encountering a strange error

image

It checks whether the `enqueueSnackbar` contains, for example, `NoAssessmentNode`, but this value was never passed to the `enqueueSnackbar` function as a warning in the `App.tsx` file or any other file. As a result, the test fails because it is looking for `NoAssessmentNode`, which does not exist. I modified the `enqueueSnackbar` function and added all the warnings to the notification, but since the value `NoAssessmentNode` was never passed to the notification, the test still fails. 
Am I missing something?

```tsx
it('Shows warning for node that failed Assessment tool option request', () => {
    cy.get('.notistack-SnackbarContainer')
      .find('.notistack-MuiContent-warning')
      .should('contain', 'NoAssessmentNode');
  });
  it('Shows warning for node that failed Diagnosis option request', () => {
    cy.get('.notistack-SnackbarContainer')
      .find('.notistack-MuiContent-warning')
      .should('contain', 'NoDiagnosisNode');
  });
  it('Shows warning for node that failed Pipeline option request', () => {
    cy.get('.notistack-SnackbarContainer')
      .find('.notistack-MuiContent-warning')
      .should('contain', 'NoPipelineNode');
  });
  it('Shows warning for node that failed Pipeline version option request', () => {
    cy.get('[data-cy="close-auth-dialog-button"]').click();
    cy.get('[data-cy="Pipeline name-categorical-field"]').type('fmri{downarrow}{enter}');
    cy.wait('@getPipelineVersionsOptions');
    cy.get('.notistack-SnackbarContainer')
      .find('.notistack-MuiContent-warning')
      .should('contain', 'NoPipelineVersionNode');
  });
```

**Comment by Tusharjamdade** [comment]
> > Hi @Tusharjamdade, That's a good approach. Could you push your changes so I can take a look at them in context?
> 
> Hi @rmanaem,
> 
> I am encountering a strange error
> 
> image
> 
> It checks whether the `enqueueSnackbar` contains, for example, `NoAssessmentNode`, but this value was never passed to the `enqueueSnackbar` function as a warning in the `App.tsx` file or any other file. As a result, the test fails because it is looking for `NoAssessmentNode`, which does not exist. I modified the `enqueueSnackbar` function and added all the warnings to the notification, but since the value `NoAssessmentNode` was never passed to the notification, the test still fails. Am I missing something?
> 
> ```tsx
> it('Shows warning for node that failed Assessment tool option request', () => {
>     cy.get('.notistack-SnackbarContainer')
>       .find('.notistack-MuiContent-warning')
>       .should('contain', 'NoAssessmentNode');
>   });
>   it('Shows warning for node that failed Diagnosis option request', () => {
>     cy.get('.notistack-SnackbarContainer')
>       .find('.notistack-MuiContent-warning')
>       .should('contain', 'NoDiagnosisNode');
>   });
>   it('Shows warning for node that failed Pipeline option request', () => {
>     cy.get('.notistack-SnackbarContainer')
>       .find('.notistack-MuiContent-warning')
>       .should('contain', 'NoPipelineNode');
>   });
>   it('Shows warning for node that failed Pipeline version option request', () => {
>     cy.get('[data-cy="close-auth-dialog-button"]').click();
>     cy.get('[data-cy="Pipeline name-categorical-field"]').type('fmri{downarrow}{enter}');
>     cy.wait('@getPipelineVersionsOptions');
>     cy.get('.notistack-SnackbarContainer')
>       .find('.notistack-MuiContent-warning')
>       .should('contain', 'NoPipelineVersionNode');
>   });
> ```

I have resolved this issue and updated the changes. Could you please review them?

File: src/App.tsx [hunk 12]
```diff
@@ -116,26 +119,38 @@ function App() {
...
           // If any errors occurred, report them
           response.data.errors.forEach((error) => {
-            enqueueSnackbar(`Failed to retrieve ${NBResource} options from ${error.node_name}`, {
-              variant: 'warning',
-              action,
-            });
+            setNotifications((prev) => [
+              ...prev,
+              {
+                id: prev.length + 1,
```
Comment (rmanaem) [inline src/App.tsx]: I don't think this is a safe way of setting the `id`, let's use a safer approach like UUID.

File: cypress/component/Navbar.cy.tsx [hunk 13]
```diff
@@ -24,5 +39,25 @@ describe('Navbar', () => {
...
+        cy.get('.MuiListItem-root')
+          .eq(index)
+          .within(() => {
+            cy.get('.MuiListItemText-primary').should('contain', notification.type.toUpperCase());
+            cy.get('.MuiListItemText-secondary').should('contain', notification.message);
+          });
+      });
+    });
+    cy.get('.MuiPopover-paper').trigger('keydown', { key: 'Escape' });
+    cy.get('.MuiPopover-paper').should('not.exist');
```
Comment (rmanaem) [inline cypress/component/Navbar.cy.tsx]: Very nice!

File: src/components/Navbar.tsx [hunk 14]
```diff
@@ -56,9 +92,111 @@ function Navbar({ isLoggedIn, onLogin }: { isLoggedIn: boolean; onLogin: () => v
...
+                <Button
+                  size="small"
+                  color="secondary"
+                  onClick={clearAllNotifications}
+                  sx={{
+                    textTransform: 'none',
+                    fontWeight: 'bold',
+                    '&:hover': {
+                      backgroundColor: '#f50057',
+                      color: '#fff',
```
Comment (rmanaem) [inline src/components/Navbar.tsx]: Is there a reason you're using the secondary color and a custom color for the background?

File: cypress/e2e/APIRequests.cy.ts [hunk 15]
```diff
@@ -505,9 +540,11 @@ describe('Partially successful API query requests', () => {
   it('Shows a warning for nodes that failed to return any results', () => {
     cy.get('[data-cy="submit-query-button"]').click();
     cy.wait('@call');
-    cy.get('.notistack-SnackbarContainer')
-      .find('.notistack-MuiContent-warning')
-      .should('contain', 'DidNotWorkNode');
+    cy.get("[data-cy='navbar']").find('svg[data-testid="NotificationsIcon"]').should('exist');
```
Comment (rmanaem) [inline cypress/e2e/APIRequests.cy.ts]: Feel free to add a `data-cy` to the notification button so you don't have to access it through the navbar every time.

File: cypress/component/Navbar.cy.tsx (hunk 13 above)
Comment (rmanaem) [inline cypress/component/Navbar.cy.tsx:85]: I suggest adding some assertions for the newly implemented individual notification delete and clear all features.

**Review by rmanaem — CHANGES_REQUESTED** [review]
Thanks for the great work @Tusharjamdade! The changes look great and the tests are now passing!
I left a few comments, please take a look and feel free to ping me with any questions.

File: cypress/component/Navbar.cy.tsx (hunk 13 above)
Comment (Tusharjamdade) [reply cypress/component/Navbar.cy.tsx:85]: I tried implementing the delete and clear all functionalities, but I passed a default notification list. As a result, I was unable to delete notifications, and the tests were failing. I will find a way to implement this.

File: src/components/Navbar.tsx (hunk 14 above)
Comment (Tusharjamdade) [reply src/components/Navbar.tsx]: I will remove the secondary color as it is being overridden

Comment (rmanaem) [reply src/components/Navbar.tsx]: I'd also suggest sticking with the existing color theme unless there is an issue.

File: cypress/component/Navbar.cy.tsx (hunk 13 above)
Comment (rmanaem) [reply cypress/component/Navbar.cy.tsx:85]: I see, I think the issue there is that inside the actual component, we're using the `setNotification` to update the `notifications` but inside the test, we mock that one as well.

**Comment by Tusharjamdade** [comment]
Hi @rmanaem, 
I have implemented the suggested changes. Could you please review them?

File: cypress/component/Navbar.cy.tsx [hunk 16]
```diff
@@ -1,13 +1,28 @@
...
+    return (
+      <Navbar
+        isLoggedIn
+        onLogin={() => {}}
+        notifications={notifications}
+        setNotifications={setNotifications}
+      />
+    );
+  }
+
```
Comment (rmanaem) [inline cypress/component/Navbar.cy.tsx:23]: Very nice!

**Review by rmanaem — APPROVED** [review]
Thanks for making the changes @Tusharjamdade! This is ready to merge 🧑‍🍳
