### PR TITLE
[FIX] Fixed parsing of `NB_IS_FEDERATION_API`

### LINKED ISSUE #84: `NB_IS_FEDERATION_API` is not parsed correctly
The `NB_IS_FEDERATION_API` is currently being parsed as a `string` which in JS/TS as long as it is not an empty string is considered a truthy value therefore even when the env var is set to `false` it will be parsed as `true`.

https://github.com/neurobagel/query-tool/blob/99fc5c019054aff221280b37ab1a09886721134a/src/utils/constants.ts#L12-L13

### PR DESCRIPTION
**Pull request by rmanaem**
- Closes #84 

## Checklist

_This section is for the PR reviewer_

- [x] PR has an interpretable title with a prefix (`[ENH]`, `[FIX]`, `[REF]`, `[TST]`, `[CI]`, `[MNT]`, `[INF]`, `[MODEL]`, `[DOC]`) _(see our [Contributing Guidelines](https://neurobagel.org/contributing/CONTRIBUTING#pull-request-guidelines) for more info)_
- [x] PR has a label for the release changelog or `skip-release` (to be applied by maintainers only)
- [x] PR links to GitHub issue with mention `Closes #XXXX`
- [x] Tests pass
- [x] Checks pass

For new features:

- [ ] Tests have been added

For bug fixes:

- [ ] There is at least one test that would fail under the original bug conditions.

### CODE REVIEW

File: src/components/QueryForm.tsx [hunk 1]
```diff
@@ -95,14 +95,14 @@ function QueryForm({
           />
         </div>
       )}
-      <div className={isFederationAPI && 'row-start-2'}>
+      <div className={isFederationAPI ? 'row-start-2' : ''}>
```
Comment (surchs) [inline src/components/QueryForm.tsx:98]: make computed variable with reasonable name?

Comment (surchs) [reply src/components/QueryForm.tsx:98]: So we don't have to duplicate this logic here

File: src/utils/constants.ts [hunk 2]
```diff
@@ -9,8 +9,7 @@ export const nodesURL: string = baseAPIURL.endsWith('/')
   ? `${baseAPIURL}nodes/`
   : `${baseAPIURL}/nodes/`;
 
-export const isFederationAPI: string =
-  import.meta.env.NB_IS_FEDERATION_API === undefined ? true : import.meta.env.NB_IS_FEDERATION_API;
+export const isFederationAPI: boolean = import.meta.env.NB_IS_FEDERATION_API === 'true';
```
Comment (surchs) [inline src/utils/constants.ts]: I believe this is changing the default behaviour from "undefined -> true" to "undefined -> false". Can you please

1. Confirm this is not the case / otherwise fix
2. Add explicit tests for 
  - env.NB_IS_FEDERATION_API = undefined
  - env.NB_IS_FEDERATION_API = true
  - env.NB_IS_FEDERATION_API = false

so we know for sure and don't have to worry

**Review by surchs — COMMENTED** [review]
thanks @rmanaem but this seems to change default behaviour. Could you please confirm and add tests

File: src/components/QueryForm.tsx (hunk 1 above)
Comment (rmanaem) [reply src/components/QueryForm.tsx:98]: Moving this logic outside of the layout would result in reduced readability.

Comment (surchs) [reply src/components/QueryForm.tsx:98]: could you explain how that is? If the variable was called `form_start_row`, how would that be less readable?

Comment (surchs) [reply src/components/QueryForm.tsx:98]: I am now convinced of the opposite of what I was asking for

File: src/utils/constants.ts (hunk 2 above)
Comment (rmanaem) [reply src/utils/constants.ts]: I've updated the fix so the default remains unchanged.
I wasn't able to find a similar workaround to what we used in Vue for overwriting the env vars. Here is the section of the Cypress docs that states `mount` is frameworks-specific hence why we may not be able to duplicate what we had in Vue: https://docs.cypress.io/api/commands/mount#Creating-a-New-cymount-Command

**Review by surchs — APPROVED** [review]
:cook:

**Comment by surchs** [comment]
before you merge @rmanaem, mind updating the commit message in the squashed commit:

> [Modified the fix so the default is false](https://github.com/neurobagel/query-tool/pull/88/commits/be94f6a399601fa30218a18d39f4e9bf58bfbd5c)

to instead say `true` - I blieve that's what you meant?

**Comment by rmanaem** [comment]
> to instead say `true` - I blieve that's what you meant?

Yes, good catch.

**Comment by surchs** [comment]
:rocket: PR was released in [`v0.2.0`](https://github.com/neurobagel/query-tool/releases/tag/v0.2.0) :rocket:
